name: CMake Build

on:
  push:
    branches: ["main"]
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: CMake build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create Build Environment
        shell: bash
        run: |
          python -m pip install wheel
          python -m pip install --upgrade pip "conan"
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: >-
          cmake $GITHUB_WORKSPACE
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -Dpython=False
          -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=./cmake/conan_provider.cmake

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C $BUILD_TYPE --output-on-failure

