name: Python Build

"on":
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
  pull_request:

jobs:
  from_uv:
    name: python uv installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install pys2let
        run: uv sync --all-extras --dev

      - name: run pytest
        run: uv run pytest

  from_sdist:
    name: python source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build sdist
        run: uv build --sdist

      - name: create venv
        run: uv venv 

      - name: install wheel
        run: "uv pip install dist/pys2let-*.tar.gz"

      - name: run pytests
        run: uv pip install pytest && uv run pytest

  build_wheels:
    name: Build wheels
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build wheels
        run: uv build --wheel

      - name: create venv
        run: uv venv 

      - name: install wheel
        run: "uv pip install dist/*.whl"

      - name: run pytests
        run: uv pip install pytest && uv run pytest

  publication:
    name: publish to pypi
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"

      - name: Build sdist
        run: uv build --sdist

      - name: Publish distribution 📦 to Test PyPI
        if: ${{ github.ref != 'refs/tags/v2.2.6' }}
        run: "uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ secrets.TEST_PYPI_TOKEN }}"

      - name: Publish distribution 📦 to PyPI
        if: ${{ github.ref == 'refs/tags/v2.2.6' }}
        run: "uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ secrets.PYPI_TOKEN }}"
